//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public string Motivo_alerta { get; set; }
        public int Gerente_id_emp { get; set; }
        public int Cliente_id_emp { get; set; }
        public int Actividad_id_act { get; set; }
    
        public virtual Actividad Actividad { get; set; }
    }
}
